### ISSUE TITLE
miRNA analysis crashed

### ISSUE THREAD

**Issue by blaizereal** [HCGB-IGTP/XICRA#6]
Hi,

I'm testing the pipeline with inhouse PE data (after successful trim and merge), but it crashes with the following error:

XICRA miRNA --input test_XICRA --software miraligner sRNAbench

What is your recommendation? I've run the XICRA config module, everything looks OK.

Thanks: Blaize 

 **ERROR **
b"['gff', '--sps', 'hsa', '--hairpin', '/home/blaize/miniconda3/lib/python3.8/site-packages/XICRA/modules/db_files/hairpin.fa', '--gtf', '/home/blaize/miniconda3/lib/python3.8/site-packages/XICRA/modules/db_files/hsa.gff3', '--format', 'srnabench', '-o', '/home/blaize/test_XICRA/data/20Nov25000002_C02-L2_S6/miRNA/sRNAbench_miRTop/gff', '/home/blaize/test_XICRA/data/20Nov25000002_C02-L2_S6/miRNA/sRNAbench']\n"
** ERROR **
Creating isomiRs counts for sample 20Nov25000002_C02-L2_S6
[** System: /home/blaize/miniconda3/bin/mirtop counts -o /home/blaize/test_XICRA/data/20Nov25000002_C02-L2_S6/miRNA/sRNAbench_miRTop/counts --gff /home/blaize/test_XICRA/data/20Nov25000002_C02-L2_S6/miRNA/sRNAbench_miRTop/gff/mirtop.gff --hairpin /home/blaize/miniconda3/lib/python3.8/site-packages/XICRA/modules/db_files/hairpin.fa --gtf /home/blaize/miniconda3/lib/python3.8/site-packages/XICRA/modules/db_files/hsa.gff3 --sps hsa 2>> /home/blaize/test_XICRA/data/20Nov25000002_C02-L2_S6/miRNA/sRNAbench_miRTop/20Nov25000002_C02-L2_S6.log **]
** ERROR **
b"['counts', '-o', '/home/blaize/test_XICRA/data/20Nov25000002_C02-L2_S6/miRNA/sRNAbench_miRTop/counts', '--gff', '/home/blaize/test_XICRA/data/20Nov25000002_C02-L2_S6/miRNA/sRNAbench_miRTop/gff/mirtop.gff', '--hairpin', '/home/blaize/miniconda3/lib/python3.8/site-packages/XICRA/modules/db_files/hairpin.fa', '--gtf', '/home/blaize/miniconda3/lib/python3.8/site-packages/XICRA/modules/db_files/hsa.gff3', '--sps', 'hsa']\n"
** ERROR **
Creating isomiRs export information for sample 20Nov25000002_C02-L2_S6
[** System: /home/blaize/miniconda3/bin/mirtop export -o /home/blaize/test_XICRA/data/20Nov25000002_C02-L2_S6/miRNA/sRNAbench_miRTop/export --hairpin /home/blaize/miniconda3/lib/python3.8/site-packages/XICRA/modules/db_files/hairpin.fa --gtf /home/blaize/miniconda3/lib/python3.8/site-packages/XICRA/modules/db_files/hsa.gff3 --sps hsa --format isomir /home/blaize/test_XICRA/data/20Nov25000002_C02-L2_S6/miRNA/sRNAbench_miRTop/gff/mirtop.gff 2> /home/blaize/test_XICRA/data/20Nov25000002_C02-L2_S6/miRNA/sRNAbench_miRTop/20Nov25000002_C02-L2_S6.log **]
** ERROR **
b"['export', '-o', '/home/blaize/test_XICRA/data/20Nov25000002_C02-L2_S6/miRNA/sRNAbench_miRTop/export', '--hairpin', '/home/blaize/miniconda3/lib/python3.8/site-packages/XICRA/modules/db_files/hairpin.fa', '--gtf', '/home/blaize/miniconda3/lib/python3.8/site-packages/XICRA/modules/db_files/hsa.gff3', '--sps', 'hsa', '--format', 'isomir', '/home/blaize/test_XICRA/data/20Nov25000002_C02-L2_S6/miRNA/sRNAbench_miRTop/gff/mirtop.gff']\n"
** ERROR**

**Comment by JFsanchezherrero** [comment]
Hi there,

Thank you very much for using XICRA and pointing this problem. Let's see what is going on here.

First of all, sRNAbench is not fully working. Some problems might be produce during the installation of it. Please let me know if during XICRA config it returned OK for sRNAbench.

Check previuos issue on installation and sRNAbench issues: https://github.com/HCGB-IGTP/XICRA/issues/5. So far, I would recommend to use optimir and miraligner as tools for the miRNA analysis.

On the other hand, let me know too if there is only one sample or you just set these log as an example.

My first guess would be that there is no information in the data provided to mirtop, either because sRNAbench did not work properly or due to the lack of data for this sample. 

Please, send the log and error files within folder: 
`/home/blaize/test_XICRA/data/20Nov25000002_C02-L2_S6/miRNA/sRNAbench_miRTop/`

Please let me know the answers to the questions here and any new information.

Best regards
Jose

**Comment by blaize1st** [comment]
Hi, 
thanks for the quick response! I've found this in the sRNAbench log: 
#####################################################################

     File not found: /home/blaize/SRNAbench/sRNAtoolboxDB/libs/hairpin.fa     


######################################################################

######################################################################

     File not found: /home/blaize/SRNAbench/sRNAtoolboxDB/libs/mature.fa     


######################################################################

######################################################################

     hsa -- Did not found either mature or precursor reference sequences! Make sure that you are using  the correct short species name (hsa, mmu, rno, etc). 
    
Unfortunately the http://bioinfo2.ugr.es/sRNAtoolboxDB/sRNAtoolboxDB.tgz link is dead, I can't download it and install standalone version correctly..

Bests: Blaize

**Comment by JFsanchezherrero** [comment]
Hi there Blaize,

As I thought, this is the problem that creates XICRA to crash. There is no information created using sRNAbench and mirtop crashes afterwards. I would take this into account and modify the code to double check installation and databases and prevent early crashes.

Unfortunately, sRNAbench does not depend on us and it has been a long time since we initially designed XICRA using fully working sRNAbench software and database. 

As I mentioned before,  I would recommend to use optimir and miraligner as tools for the miRNA analysis.

Best regards,
Jose

**Comment by JFsanchezherrero** [comment]
Hi there,

I wonder if you managed to use XICRA with your data or if you need additional help.

Best regards
Jose
